Diagram:
  DefinitionFiles:
    - Type: URL
      Url: "https://raw.githubusercontent.com/awslabs/diagram-as-code/main/definitions/definition-for-aws-icons-light.yaml"

  Resources:
    Canvas:
      Type: AWS::Diagram::Canvas
      Children:
        - Resource1
        - Resource2
    
    # 共通祖先がCanvasの場合
    Resource1:
      Type: AWS::EC2::Instance
      Title: "Instance 1"
    
    Resource2:
      Type: AWS::EC2::Instance
      Title: "Instance 2"

  Links:
    - Source: Resource1
      Target: Resource2
      Type: orthogonal
      TargetArrowHead:
        Type: Open
