Diagram:
  DefinitionFiles:
    - Type: URL
      Url: "https://raw.githubusercontent.com/awslabs/diagram-as-code/main/definitions/definition-for-aws-icons-light.yaml"

  Resources:
    Canvas:
      Type: AWS::Diagram::Canvas
      Direction: vertical
      Children:
        - AWSCloud
    
    AWSCloud:
      Type: AWS::Diagram::Cloud
      Direction: vertical
      Preset: AWSCloudNoLogo
      Align: center
      Children:
        - HorizontalGroup
    
    HorizontalGroup:
      Type: AWS::Diagram::HorizontalStack
      Align: center
      Children:
        - LoadBalancer
        - ServiceGroup
    
    LoadBalancer:
      Type: AWS::ElasticLoadBalancingV2::LoadBalancer
      Title: "Load Balancer"
    
    ServiceGroup:
      Type: AWS::Diagram::VerticalStack
      Align: center
      Children:
        - Service1
        - Service2
        - Service3
    
    Service1:
      Type: AWS::Lambda::Function
      Title: "Web Service"
    
    Service2:
      Type: AWS::Lambda::Function
      Title: "API Service"
    
    Service3:
      Type: AWS::Lambda::Function
      Title: "Auth Service"

  Links:
    - Source: LoadBalancer
      Target: Service1
      Type: orthogonal
      TargetArrowHead:
        Type: Open
    
    - Source: LoadBalancer
      Target: Service2
      Type: orthogonal
      TargetArrowHead:
        Type: Open
    
    - Source: LoadBalancer
      Target: Service3
      Type: orthogonal
      TargetArrowHead:
        Type: Open
