Diagram:
  DefinitionFiles:
    - Type: URL
      Url: "https://raw.githubusercontent.com/awslabs/diagram-as-code/main/definitions/definition-for-aws-icons-light.yaml"

  Resources:
    Canvas:
      Type: AWS::Diagram::Canvas
      Direction: vertical
      Children:
        - AWSCloud
    
    AWSCloud:
      Type: AWS::Diagram::Cloud
      Direction: vertical
      Preset: AWSCloudNoLogo
      Align: center
      Children:
        - Region
    
    Region:
      Type: AWS::Diagram::VerticalStack
      Children:
        - PublicTier
        - PrivateTier
    
    PublicTier:
      Type: AWS::Diagram::HorizontalStack
      Align: center
      Children:
        - ALB
        - NAT1
        - NAT2
    
    PrivateTier:
      Type: AWS::Diagram::HorizontalStack
      Align: center
      Children:
        - App1
        - App2
        - App3
    
    ALB:
      Type: AWS::ElasticLoadBalancingV2::LoadBalancer
      Title: "ALB"
    
    NAT1:
      Type: AWS::EC2::NatGateway
      Title: "NAT Gateway 1"
    
    NAT2:
      Type: AWS::EC2::NatGateway
      Title: "NAT Gateway 2"
    
    App1:
      Type: AWS::EC2::Instance
      Title: "App Server 1"
    
    App2:
      Type: AWS::EC2::Instance
      Title: "App Server 2"
    
    App3:
      Type: AWS::EC2::Instance
      Title: "App Server 3"

  Links:
    # Cross-tier connections (should be vertical due to Region being VerticalStack)
    - Source: ALB
      Target: App1
      Type: orthogonal
      TargetArrowHead:
        Type: Open
    
    - Source: ALB
      Target: App2
      Type: orthogonal
      TargetArrowHead:
        Type: Open
    
    - Source: ALB
      Target: App3
      Type: orthogonal
      TargetArrowHead:
        Type: Open
