Diagram:
  DefinitionFiles:
    - Type: URL
      Url: "https://raw.githubusercontent.com/awslabs/diagram-as-code/main/definitions/definition-for-aws-icons-light.yaml"

  Resources:
    Canvas:
      Type: AWS::Diagram::Canvas
      Direction: horizontal
      Children:
        - LeftStack
        - MiddleStack
        - RightStack

    LeftStack:
      Type: AWS::Diagram::VerticalStack
      Children:
        - SourceResource

    MiddleStack:
      Type: AWS::Diagram::VerticalStack
      Children:
        - MiddleResource

    RightStack:
      Type: AWS::Diagram::VerticalStack
      Children:
        - TargetResource1
        - TargetResource2

    SourceResource:
      Type: AWS::EC2::Instance
      Title: Source

    MiddleResource:
      Type: AWS::EC2::Instance
      Title: Middle

    TargetResource1:
      Type: AWS::EC2::Instance
      Title: Target 1

    TargetResource2:
      Type: AWS::EC2::Instance
      Title: Target 2

  Links:
    # Test case 1: Source to Target1 - should create L-shaped path
    - Source: SourceResource
      Target: TargetResource1
      Type: orthogonal
      Labels:
        AutoRight:
          Title: "R1"
        AutoLeft:
          Title: "L1"

    # Test case 2: Source to Target2 - should create different L-shaped path
    - Source: SourceResource
      Target: TargetResource2
      Type: orthogonal
      Labels:
        AutoRight:
          Title: "R2"
        AutoLeft:
          Title: "L2"

    # Test case 3: Middle to Target1 - should create horizontal path
    - Source: MiddleResource
      Target: TargetResource1
      Type: orthogonal
      Labels:
        AutoRight:
          Title: "MR1"
        AutoLeft:
          Title: "ML1"
