Diagram:
  DefinitionFiles:
    - Type: URL
      Url: "https://raw.githubusercontent.com/awslabs/diagram-as-code/main/definitions/definition-for-aws-icons-light.yaml"
    #- Type: LocalFile
    #  LocalFile: ./definitions/definition-for-aws-icons-light.yaml

  Resources:
    Canvas:
      Type: AWS::Diagram::Canvas
      Direction: vertical
      Children:
        - AWSCloud
        - User
    AWSCloud:
      Type: AWS::Diagram::Cloud
      Direction: vertical
      Preset: AWSCloudNoLogo
      Align: center
      Children:
        - Regions
    Regions:
      Type: AWS::Diagram::HorizontalStack
      Children:
        - OregonRegion
        - VirginiaRegion

    #
    # Oregon Region
    #
    OregonRegion:
      Type: AWS::Region
      Direction: vertical
      Title: us-west-2
      Children:
        - OregonVPC
    OregonVPC:
      Type: AWS::EC2::VPC
      Direction: vertical
      Title: VPC
      Children:
        - OregonVPCPublicStack
        - OregonALB
      BorderChildren:
        - Position: S
          Resource: OregonIGW
    OregonVPCPublicStack:
      Type: AWS::Diagram::HorizontalStack
      Children:
        - OregonVPCPublicSubnet1
        - OregonVPCPublicSubnet2
    OregonVPCPublicSubnet1:
      Type: AWS::EC2::Subnet
      Preset: PublicSubnet
      Children:
        - OregonVPCPublicSubnet1Instance
    OregonVPCPublicSubnet1Instance:
      Type: AWS::EC2::Instance
    OregonVPCPublicSubnet2:
      Type: AWS::EC2::Subnet
      Preset: PublicSubnet
      Children:
        - OregonVPCPublicSubnet2Instance
    OregonVPCPublicSubnet2Instance:
      Type: AWS::EC2::Instance
    OregonALB:
      Type: AWS::ElasticLoadBalancingV2::LoadBalancer
      Preset: Application Load Balancer
    OregonIGW:
      Type: AWS::EC2::InternetGateway
      IconFill:
        Type: rect

    #
    # Virginia Region
    #
    VirginiaRegion:
      Type: AWS::Region
      Direction: vertical
      Title: us-east-1
      Children:
        - VirginiaVPC
    VirginiaVPC:
      Type: AWS::EC2::VPC
      Direction: vertical
      Title: VPC
      Children:
        - VirginiaVPCPublicStack
        - VirginiaALB
      BorderChildren:
        - Position: S
          Resource: VirginiaIGW
    VirginiaVPCPublicStack:
      Type: AWS::Diagram::HorizontalStack
      Children:
        - VirginiaVPCPublicSubnet1
        - VirginiaVPCPublicSubnet2
    VirginiaVPCPublicSubnet1:
      Type: AWS::EC2::Subnet
      Preset: PublicSubnet
      Children:
        - VirginiaVPCPublicSubnet1Instance
    VirginiaVPCPublicSubnet1Instance:
      Type: AWS::EC2::Instance
    VirginiaVPCPublicSubnet2:
      Type: AWS::EC2::Subnet
      Preset: PublicSubnet
      Children:
        - VirginiaVPCPublicSubnet2Instance
    VirginiaVPCPublicSubnet2Instance:
      Type: AWS::EC2::Instance
    VirginiaALB:
      Type: AWS::ElasticLoadBalancingV2::LoadBalancer
      Preset: Application Load Balancer
    VirginiaIGW:
      Type: AWS::EC2::InternetGateway
      IconFill:
        Type: rect

    User:
      Type: AWS::Diagram::Resource
      Preset: User

  Links:
    - Source: OregonALB
      SourcePosition: W
      Target: OregonVPCPublicSubnet1Instance
      TargetPosition: S
      TargetArrowHead:
        Type: Open
      Type: orthogonal
    - Source: OregonALB
      SourcePosition: E
      Target: OregonVPCPublicSubnet2Instance
      TargetPosition: S
      TargetArrowHead:
        Type: Open
      Type: orthogonal
    - Source: OregonIGW
      SourcePosition: N
      Target: OregonALB
      TargetPosition: S
      TargetArrowHead:
        Type: Open
    - Source: User
      SourcePosition: W
      Target: OregonIGW
      TargetPosition: S
      TargetArrowHead:
        Type: Open
      Type: orthogonal
    - Source: VirginiaALB
      SourcePosition: W
      Target: VirginiaVPCPublicSubnet1Instance
      TargetPosition: S
      TargetArrowHead:
        Type: Open
      Type: orthogonal
    - Source: VirginiaALB
      SourcePosition: E
      Target: VirginiaVPCPublicSubnet2Instance
      TargetPosition: S
      TargetArrowHead:
        Type: Open
      Type: orthogonal
    - Source: VirginiaIGW
      SourcePosition: N
      Target: VirginiaALB
      TargetPosition: S
      TargetArrowHead:
        Type: Open
    - Source: User
      SourcePosition: E
      Target: VirginiaIGW
      TargetPosition: S
      TargetArrowHead:
        Type: Open
      Type: orthogonal
