Diagram:
  DefinitionFiles:
    - Type: URL
      Url: "https://raw.githubusercontent.com/awslabs/diagram-as-code/main/definitions/definition-for-aws-icons-light.yaml"
    #- Type: LocalFile
    #  LocalFile: ./definitions/definition-for-aws-icons-light.yaml

  Resources:
    Canvas:
      Type: AWS::Diagram::Canvas
      Direction: vertical
      Children:
        - AWSCloud
        - User
    AWSCloud:
      Type: AWS::Diagram::Cloud
      Direction: vertical
      Align: center
      Children:
        - HorizontalStack1
        - HorizontalStack2
    HorizontalStack1:
      Type: AWS::Diagram::HorizontalStack
      Children:
        - VPC1
        - TransitGateway
        - VPC2

    # VPC1
    VPC1:
      Type: AWS::EC2::VPC
      Direction: vertical
      Title: "VPC1 (10.0.0.0/16)"
      Children:
        - VPC1AvailabilityZone1
        - VPC1AvailabilityZone2
      BorderChildren:
        - Position: E
          Resource: VPC1TGWAttach
        - Position: W
          Resource: VPC1IGW

    VPC1AvailabilityZone1:
      Type: AWS::EC2::AvailabilityZone
      Direction: horizontal
      Title: Availability Zone 1
      Children:
        - VPC1PublicSubnet1
        - VPC1TransitSubnet1
    VPC1PublicSubnet1:
      Type: AWS::EC2::Subnet
      Preset: PublicSubnet
      Children:
        - VPC1PublicSubnet1Instance
    VPC1PublicSubnet1Instance:
      Type: AWS::EC2::Instance
    VPC1TransitSubnet1:
      Type: AWS::EC2::Subnet
      Preset: PrivateSubnet
      Children:
        - VPC1TransitSubnet1Eni
    VPC1TransitSubnet1Eni:
      Type: AWS::EC2::NetworkInterface
      Title: "TGW ENI"

    VPC1AvailabilityZone2:
      Type: AWS::EC2::AvailabilityZone
      Direction: horizontal
      Title: Availability Zone 2
      Children:
        - VPC1PublicSubnet2
        - VPC1TransitSubnet2
    VPC1PublicSubnet2:
      Type: AWS::EC2::Subnet
      Preset: PublicSubnet
      Children:
        - VPC1PublicSubnet2Instance
    VPC1PublicSubnet2Instance:
      Type: AWS::EC2::Instance
    VPC1TransitSubnet2:
      Type: AWS::EC2::Subnet
      Preset: PrivateSubnet
      Children:
        - VPC1TransitSubnet2Eni
    VPC1TransitSubnet2Eni:
      Type: AWS::EC2::NetworkInterface
      Title: "TGW ENI"
    VPC1TGWAttach:
      Type: AWS::EC2::TransitGatewayAttachment
      IconFill:
        Type: rect
    VPC1IGW:
      Type: AWS::EC2::InternetGateway
      IconFill:
        Type: rect

    # Transit Gateway
    TransitGateway:
      Type: AWS::EC2::TransitGateway

    # VPC2
    VPC2:
      Type: AWS::EC2::VPC
      Title: "VPC2 (10.1.0.0/16)"
      Direction: vertical
      Children:
        - VPC2AvailabilityZone1
        - VPC2AvailabilityZone2
      BorderChildren:
        - Position: W
          Resource: VPC2TGWAttach
        - Position: E
          Resource: VPC2IGW
    VPC2AvailabilityZone1:
      Type: AWS::EC2::AvailabilityZone
      Direction: horizontal
      Title: Availability Zone 1
      Children:
        - VPC2TransitSubnet1
        - VPC2PublicSubnet1
    VPC2TransitSubnet1:
      Type: AWS::EC2::Subnet
      Preset: PrivateSubnet
      Children:
        - VPC2TransitSubnet1Eni
    VPC2TransitSubnet1Eni:
      Type: AWS::EC2::NetworkInterface
      Title: "TGW ENI"
    VPC2PublicSubnet1:
      Type: AWS::EC2::Subnet
      Preset: PublicSubnet
      Children:
        - VPC2PublicSubnet1Instance
    VPC2PublicSubnet1Instance:
      Type: AWS::EC2::Instance

    VPC2AvailabilityZone2:
      Type: AWS::EC2::AvailabilityZone
      Direction: horizontal
      Title: Availability Zone 2
      Children:
        - VPC2TransitSubnet2
        - VPC2PublicSubnet2
    VPC2PublicSubnet2:
      Type: AWS::EC2::Subnet
      Preset: PublicSubnet
      Children:
        - VPC2PublicSubnet2Instance
    VPC2PublicSubnet2Instance:
      Type: AWS::EC2::Instance
    VPC2TransitSubnet2:
      Type: AWS::EC2::Subnet
      Preset: PrivateSubnet
      Children:
        - VPC2TransitSubnet2Eni
    VPC2TransitSubnet2Eni:
      Type: AWS::EC2::NetworkInterface
      Title: "TGW ENI"
    VPC2TGWAttach:
      Type: AWS::EC2::TransitGatewayAttachment
      IconFill:
        Type: rect
    VPC2IGW:
      Type: AWS::EC2::InternetGateway
      IconFill:
        Type: rect

    HorizontalStack2:
      Type: AWS::Diagram::HorizontalStack
      Align: bottom
      Children:
        - VPC3
    # VPC3
    VPC3:
      Type: AWS::EC2::VPC
      Direction: horizontal
      Align: center
      Title: "VPC3 (10.2.0.0/16)"
      Children:
        - VPC3AvailabilityZone1
        - VPC3AvailabilityZone2
      BorderChildren:
        - Position: N
          Resource: VPC3TGWAttach
    VPC3AvailabilityZone1:
      Type: AWS::EC2::AvailabilityZone
      Direction: vertical
      Title: Availability Zone 1
      Children:
        - VPC3TransitSubnet1
        - VPC3FirewallSubnet1
    VPC3TransitSubnet1:
      Type: AWS::EC2::Subnet
      Preset: PrivateSubnet
      Children:
        - VPC3TransitSubnet1Eni
    VPC3TransitSubnet1Eni:
      Type: AWS::EC2::NetworkInterface
      Title: "TGW ENI"
    VPC3FirewallSubnet1:
      Type: AWS::EC2::Subnet
      Preset: PrivateSubnet
      Title: "Firewall Subnet"
      FillColor: "rgba(150,115,166,75)"
      Children:
        - VPC3FirewallSubnet1Vpce
    VPC3FirewallSubnet1Vpce:
      Type: AWS::EC2::VPCEndpoint
      Title: "Firewall Endpoint"

    VPC3AvailabilityZone2:
      Type: AWS::EC2::AvailabilityZone
      Direction: vertical
      Title: Availability Zone 2
      Children:
        - VPC3TransitSubnet2
        - VPC3FirewallSubnet2
    VPC3TransitSubnet2:
      Type: AWS::EC2::Subnet
      Preset: PrivateSubnet
      Children:
        - VPC3TransitSubnet2Eni
    VPC3TransitSubnet2Eni:
      Type: AWS::EC2::NetworkInterface
      Title: "TGW ENI"
    VPC3FirewallSubnet2:
      Type: AWS::EC2::Subnet
      Preset: PrivateSubnet
      Title: "Firewall Subnet"
      FillColor: "rgba(150,115,166,75)"
      Children:
        - VPC3FirewallSubnet2Vpce
    VPC3FirewallSubnet2Vpce:
      Type: AWS::EC2::VPCEndpoint
      Title: "Firewall Endpoint"
    VPC3TGWAttach:
      Type: AWS::EC2::TransitGatewayAttachment
      IconFill:
        Type: rect
    User:
      Type: AWS::Diagram::Resource
      Preset: "User"

  Links:
    - Source: TransitGateway
      SourcePosition: W
      Target: VPC1TGWAttach
      TargetPosition: E
      LinkType: double
    - Source: TransitGateway
      SourcePosition: E
      Target: VPC2TGWAttach
      TargetPosition: W
      LinkType: double
    - Source: TransitGateway
      SourcePosition: S
      Target: VPC3TGWAttach
      TargetPosition: N
