Diagram:
  DefinitionFiles:
    - Type: URL
      Url: "https://raw.githubusercontent.com/awslabs/diagram-as-code/main/definitions/definition-for-aws-icons-light.yaml"
    #- Type: LocalFile
    #  LocalFile: ./definitions/definition-for-aws-icons-light.yaml

  Resources:
    Canvas:
      Type: AWS::Diagram::Canvas
      Direction: vertical
      Children:
        - AWSCloud
        - User
    AWSCloud:
      Type: AWS::Diagram::Cloud
      Direction: vertical
      Align: center
      Children:
        - HorizontalStack1
        - HorizontalStack2
    HorizontalStack1:
      Type: AWS::Diagram::HorizontalStack
      Children:
        - VPC1
        - TransitGateway
        - VPC2

    # VPC1
    VPC1:
      Type: AWS::EC2::VPC
      Title: "VPC1 (10.0.0.0/16)"
      Children:
        - VPC1PublicStack
        - VPC1TransitStack

    VPC1PublicStack:
      Type: AWS::Diagram::VerticalStack
      Children:
        - VPC1PublicSubnet1
        - VPC1PublicSubnet2
    VPC1PublicSubnet1:
      Type: AWS::EC2::Subnet
      Preset: PublicSubnet
      Children:
        - VPC1PublicSubnet1Instance
    VPC1PublicSubnet1Instance:
      Type: AWS::EC2::Instance
    VPC1PublicSubnet2:
      Type: AWS::EC2::Subnet
      Preset: PublicSubnet
      Children:
        - VPC1PublicSubnet2Instance
    VPC1PublicSubnet2Instance:
      Type: AWS::EC2::Instance

    VPC1TransitStack:
      Type: AWS::Diagram::VerticalStack
      Children:
        - VPC1TransitSubnet1
        - VPC1TransitSubnet2
    VPC1TransitSubnet1:
      Type: AWS::EC2::Subnet
      Preset: PrivateSubnet
      Children:
        - VPC1TransitSubnet1Eni
    VPC1TransitSubnet1Eni:
      Type: AWS::EC2::NetworkInterface
      Title: "TGW ENI"
    VPC1TransitSubnet2:
      Type: AWS::EC2::Subnet
      Preset: PrivateSubnet
      Children:
        - VPC1TransitSubnet2Eni
    VPC1TransitSubnet2Eni:
      Type: AWS::EC2::NetworkInterface
      Title: "TGW ENI"

    # Transit Gateway
    TransitGateway:
      Type: AWS::EC2::TransitGateway

    # VPC2
    VPC2:
      Type: AWS::EC2::VPC
      Title: "VPC2 (10.1.0.0/16)"
      Children:
        - VPC2TransitStack
        - VPC2PublicStack

    VPC2TransitStack:
      Type: AWS::Diagram::VerticalStack
      Children:
        - VPC2TransitSubnet1
        - VPC2TransitSubnet2
    VPC2TransitSubnet1:
      Type: AWS::EC2::Subnet
      Preset: PrivateSubnet
      Children:
        - VPC2TransitSubnet1Eni
    VPC2TransitSubnet1Eni:
      Type: AWS::EC2::NetworkInterface
      Title: "TGW ENI"
    VPC2TransitSubnet2:
      Type: AWS::EC2::Subnet
      Preset: PrivateSubnet
      Children:
        - VPC2TransitSubnet2Eni
    VPC2TransitSubnet2Eni:
      Type: AWS::EC2::NetworkInterface
      Title: "TGW ENI"

    VPC2PublicStack:
      Type: AWS::Diagram::VerticalStack
      Children:
        - VPC2PublicSubnet1
        - VPC2PublicSubnet2
    VPC2PublicSubnet1:
      Type: AWS::EC2::Subnet
      Preset: PublicSubnet
      Children:
        - VPC2PublicSubnet1Instance
    VPC2PublicSubnet1Instance:
      Type: AWS::EC2::Instance
    VPC2PublicSubnet2:
      Type: AWS::EC2::Subnet
      Preset: PublicSubnet
      Children:
        - VPC2PublicSubnet2Instance
    VPC2PublicSubnet2Instance:
      Type: AWS::EC2::Instance
    HorizontalStack2:
      Type: AWS::Diagram::HorizontalStack
      Align: bottom
      Children:
        - IGW1
        - Empty1
        - VPC3
        - Empty2
        - IGW2
    IGW1:
      Type: AWS::EC2::InternetGateway
    Empty1:
      Type: AWS::Diagram::Resource
    # VPC3
    VPC3:
      Type: AWS::EC2::VPC
      Direction: vertical
      Align: center
      Title: "VPC3 (10.2.0.0/16)"
      Children:
        - VPC3TransitStack
        - VPC3FirewallStack

    VPC3TransitStack:
      Type: AWS::Diagram::HorizontalStack
      Children:
        - VPC3TransitSubnet1
        - VPC3TransitSubnet2
    VPC3TransitSubnet1:
      Type: AWS::EC2::Subnet
      Preset: PrivateSubnet
      Children:
        - VPC3TransitSubnet1Eni
    VPC3TransitSubnet1Eni:
      Type: AWS::EC2::NetworkInterface
      Title: "TGW ENI"
    VPC3TransitSubnet2:
      Type: AWS::EC2::Subnet
      Preset: PrivateSubnet
      Children:
        - VPC3TransitSubnet2Eni
    VPC3TransitSubnet2Eni:
      Type: AWS::EC2::NetworkInterface
      Title: "TGW ENI"

    VPC3FirewallStack:
      Type: AWS::Diagram::HorizontalStack
      Children:
        - VPC3FirewallSubnet1
        - VPC3FirewallSubnet2
    VPC3FirewallSubnet1:
      Type: AWS::EC2::Subnet
      Preset: PrivateSubnet
      Title: "Firewall Subnet"
      FillColor: "rgba(150,115,166,75)"
      Children:
        - VPC3FirewallSubnet1Vpce
    VPC3FirewallSubnet1Vpce:
      Type: AWS::EC2::VPCEndpoint
      Title: "Firewall Endpoint"
    VPC3FirewallSubnet2:
      Type: AWS::EC2::Subnet
      Preset: PrivateSubnet
      Title: "Firewall Subnet"
      FillColor: "rgba(150,115,166,75)"
      Children:
        - VPC3FirewallSubnet2Vpce
    VPC3FirewallSubnet2Vpce:
      Type: AWS::EC2::VPCEndpoint
      Title: "Firewall Endpoint"
    Empty2:
      Type: AWS::Diagram::Resource
    IGW2:
      Type: AWS::EC2::InternetGateway

    User:
      Type: AWS::Diagram::Resource
      Preset: "User"

  Links:
    - Source: TransitGateway
      SourcePosition: W
      Target: VPC1
      TargetPosition: E
      LinkType: double
    - Source: TransitGateway
      SourcePosition: E
      Target: VPC2
      TargetPosition: W
      LinkType: double
    - Source: TransitGateway
      SourcePosition: S
      Target: VPC3
      TargetPosition: N
