Diagram:
  DefinitionFiles:
    - Type: LocalFile
      LocalFile: "./definitions/definition-for-aws-icons-light.yaml"
  Resources:
    Canvas:
      Type: AWS::Diagram::Canvas
      Direction: vertical
      Children:
        - AWSCloud
        - User
    AWSCloud:
      Type: AWS::Diagram::Cloud
      Direction: vertical
      Align: center
      Children:
        - VPC

    # VPC
    VPC:
      Type: AWS::EC2::VPC
      Title: "VPC"
      Direction: vertical
      Children:
        - VPCPublicSubnetStack
        - VPCPrivateSubnetStack

    VPCPublicSubnetStack:
      Type: AWS::Diagram::HorizontalStack
      Children:
        - VPCPublicSubnet1
        - VPCPublicSubnet2
    VPCPublicSubnet1:
      Type: AWS::EC2::Subnet
      Preset: PublicSubnet
      Title: "Public Subnet"
      Children:
        - VPCPublicSubnet1NatGateway
    VPCPublicSubnet1NatGateway:
      Type: AWS::EC2::NatGateway
      Title: "NAT Gateway"
    VPCPublicSubnet2:
      Type: AWS::EC2::Subnet
      Preset: PublicSubnet
      Title: "Public Subnet"
      Children:
        - VPCPublicSubnet2NatGateway
    VPCPublicSubnet2NatGateway:
      Type: AWS::EC2::NatGateway
      Title: "NAT Gateway"

    VPCPrivateSubnetStack:
      Type: AWS::Diagram::HorizontalStack
      Children:
        - VPCPrivateSubnet1
        - VPCPrivateSubnet2
    VPCPrivateSubnet1:
      Type: AWS::EC2::Subnet
      Preset: PrivateSubnet
      Title: "Private Subnet"
      Children:
        - VPCPrivateSubnet1Instance
    VPCPrivateSubnet1Instance:
      Type: AWS::EC2::Instance
      Title: "EC2 Instance"
    VPCPrivateSubnet2:
      Type: AWS::EC2::Subnet
      Preset: PrivateSubnet
      Title: "Private Subnet"
      Children:
        - VPCPrivateSubnet2Instance
    VPCPrivateSubnet2Instance:
      Type: AWS::EC2::Instance
      Title: "EC2 Instance"

    User:
      Type: AWS::Diagram::Resource
      Preset: User
      Title: "User"
