Diagram:
  DefinitionFiles:
    - Type: URL
      Url: "https://raw.githubusercontent.com/awslabs/diagram-as-code/main/definitions/definition-for-aws-icons-light.yaml"
    #- Type: LocalFile
    #  LocalFile: ./definitions/definition-for-aws-icons-light.yaml
  Resources:
    Canvas:
      Type: AWS::Diagram::Canvas
      Direction: vertical
      Children:
        - AWSCloud
        - User
    AWSCloud:
      Type: AWS::Diagram::Cloud
      Direction: vertical
      Preset: AWSCloudNoLogo
      Align: center
      Children:
        - VPC

    # VPC
    VPC:
      Type: AWS::EC2::VPC
      Direction: vertical
      Children:
        - VPCPublicSubnetStack
        - VPCPrivateSubnetStack

    VPCPublicSubnetStack:
      Type: AWS::Diagram::HorizontalStack
      Children:
        - VPCPublicSubnet1
        - VPCPublicSubnet2
    VPCPublicSubnet1:
      Type: AWS::EC2::Subnet
      Preset: Public subnet
      Children:
        - VPCPublicSubnet1NatGateway
    VPCPublicSubnet1NatGateway:
      Type: AWS::EC2::NatGateway
    VPCPublicSubnet2:
      Type: AWS::EC2::Subnet
      Preset: Public subnet
      Children:
        - VPCPublicSubnet2NatGateway
    VPCPublicSubnet2NatGateway:
      Type: AWS::EC2::NatGateway

    VPCPrivateSubnetStack:
      Type: AWS::Diagram::HorizontalStack
      Children:
        - VPCPrivateSubnet1
        - VPCPrivateSubnet2
    VPCPrivateSubnet1:
      Type: AWS::EC2::Subnet
      Preset: Private subnet
      Children:
        - VPCPrivateSubnet1Instance
    VPCPrivateSubnet1Instance:
      Type: AWS::EC2::Instance
    VPCPrivateSubnet2:
      Type: AWS::EC2::Subnet
      Preset: Private subnet
      Children:
        - VPCPrivateSubnet2Instance
    VPCPrivateSubnet2Instance:
      Type: AWS::EC2::Instance

    User:
      Type: AWS::Diagram::Resource
      Preset: User
