name: Regenerate example images

on: issue_comment

jobs:
  regenerate-images:
    runs-on: ubuntu-latest
    permissions: write-all
    if: (github.event.issue.pull_request != null) && startsWith(github.event.comment.body, '/approve-breaking-changes-regenerate-example-images')

    steps:
      - name: Checkout main
        uses: actions/checkout@v3
        with:
          ref: "${{ github.event.pull_request.merge_commit_sha }}"

      - name: Checkout Pull Request
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PR_URL="${{ github.event.issue.pull_request.url }}"
          PR_NUM=${PR_URL##*/}
          echo "Checking out from PR #$PR_NUM based on URL: $PR_URL"
          gh pr checkout $PR_NUM

      - name: Check the reason
        env:
          PR_NUMBER: ${{ github.event.issue.number }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          reason=$(echo "${{ github.event.comment.body }}" | awk '{print $2}')
          if [[ "$reason" == "" ]]; then
              gh pr comment "${PR_NUMBER}" -b "No reason given, failed to regenerate example images. Use command syntax `/approve-breaking-changes-regenerate-example-images <REASON>`"
              exit 1
          fi
          gh pr comment "${PR_NUMBER}" -b "Regenerating example images..."

      - name: Setup Go 1.21.x
        uses: actions/setup-go@v5
        with:
          # Semantic version range syntax or exact version of Go
          go-version: '1.21.x'

      - name: Install dependencies
        run: |
          sudo apt-get update
          echo ttf-mscorefonts-installer msttcorefonts/accepted-mscorefonts-eula select true | sudo debconf-set-selections
          sudo apt-get install -y ttf-mscorefonts-installer

      - name: Build
        run: |
          go build -buildvcs=false -ldflags="-w" ./cmd/awsdac

      - name: Overwrite example images
        id: staging
        run: |
          find ./examples/ -name *.yaml | grep -v "cfn.yaml" | xargs -I_ yq -i '.Diagram.DefinitionFiles[0].Type="LocalFile" | del(.Diagram.DefinitionFiles[0].Url) | .Diagram.DefinitionFiles[0].LocalFile="./definitions/definition-for-aws-icons-light.yaml"' _
          find examples -type f -name "*.yaml" | while read yamlFile
          do
            pngFile=$(echo "$yamlFile" | sed 's/.yaml/.png/g')
            if [[ "$yamlFile" =~ cfn.yaml$ ]]; then
              ./awsdac --cfn-template "$yamlFile" --dac-file
              yq -i '.Diagram.DefinitionFiles[0].Type="LocalFile" | del(.Diagram.DefinitionFiles[0].Url) | .Diagram.DefinitionFiles[0].LocalFile="./definitions/definition-for-aws-icons-light.yaml"' output.yaml
              ./awsdac "output.yaml" -o "$pngFile"
            else
              ./awsdac "$yamlFile" -o "$pngFile"
            fi
          done
          git add ./examples/*.png
          git status
          echo "CHANGES=$(git diff --staged --name-only | wc -l)" >> $GITHUB_OUTPUT

      - name: Push changes
        if: steps.staging.outputs.CHANGES > 0
        env:
          PR_NUMBER: ${{ github.event.issue.number }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git commit -F- <<EOS
          bot: Overwrite example images by manual approval

          BREAKING CHNAGES: examples/*.png

          Refs: #${PR_NUMBER}"
          EOS
          git push
          gh pr comment "${PR_NUMBER}" -b "Completed to overwrite ${{ steps.staging.outputs.CHANGES }} example images."
