on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

name: E2E test

jobs:
  build:
    name: Test
    runs-on: ubuntu-22.04
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Go 1.21.x
        uses: actions/setup-go@v5
        with:
          # Semantic version range syntax or exact version of Go
          go-version: '1.21.x'

      - name: Install dependencies
        run: |
          sudo apt-get update
          echo ttf-mscorefonts-installer msttcorefonts/accepted-mscorefonts-eula select true | sudo debconf-set-selections
          sudo apt-get install -y ttf-mscorefonts-installer

      - name: Unit tests
        run: go test ./internal/...

      - name: Functional tests
        run: go test ./test/...

      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: upload results
          path: /tmp/results/
