on:
  push:
    branches: [ '**' ]
    paths:
      - '**/*.go'
      - 'go.mod'
      - 'go.sum'
      - '.github/workflows/unit_test.yaml'
  pull_request:
    branches: [ '**' ]
    paths:
      - '**/*.go'
      - 'go.mod'
      - 'go.sum'
  workflow_dispatch:

name: Unit test

jobs:
  build:
    name: Test
    permissions:
      contents: read
    runs-on: ubuntu-22.04
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Go 1.21.x
        uses: actions/setup-go@v5
        with:
          # Semantic version range syntax or exact version of Go
          go-version: '1.21.x'

      - name: Install dependencies
        run: |
          sudo apt-get update
          echo ttf-mscorefonts-installer msttcorefonts/accepted-mscorefonts-eula select true | sudo debconf-set-selections
          sudo apt-get install -y ttf-mscorefonts-installer

      - name: Unit tests
        run: |
          go test -v ./internal/...
          go test -v ./cmd/awsdac-mcp-server/...

      - name: Build awsdac-mcp-server
        run: go build -v ./cmd/awsdac-mcp-server
